// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class AddressResponseDTO
    {
        public string AddressValue { get; private set; }

        public int Number { get; private set; }

        public string Neighborhood { get; private set; }

        public string Cep { get; private set; }

        public AddressResponseDTO(string addressValue, int number, string neighborhood, string cep)
        {
            AddressValue = addressValue;
            Number = number;
            Neighborhood = neighborhood;
            Cep = cep;
        }
    }
}