// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using UniVerseAPI.Application.DTOs.Response.BaseResponse;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class ClaimsPrincipalDTO : BaseResponseDTO
    {
        public ClaimsPrincipal Claims { get; set; }

        public ClaimsPrincipalDTO()
        {
            
        }
    }
}