// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class PeopleResponseDTO
    {
 
        public string FullName { get; private set; }
        public DateTime BirthDate { get; private set; }
        public string Cpf { get; private set; }
        public string Gender { get; private set; }
        public string Phone { get; private set; }
        public string Email { get; private set; }
        public string Password { get; set; }

        public PeopleResponseDTO(string fullName, DateTime birthDate, string cpf, string gender, string phone, string email, string password)
        {
            FullName = fullName;
            BirthDate = birthDate;
            Cpf = cpf;
            Gender = gender;
            Phone = phone;
            Email = email;
            Password = password;
        }
    }


}