// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class BaseEntity
    {
        public bool? Deleted { get; protected set; }
        public bool? Active { get; protected set; }
        public DateTime CreationDate { get; protected set; }
        public DateTime LastUpdate { get; protected set; }

        public void DeleteAsync()
        {
            Deleted = true;
            LastUpdate = DateTime.Now;
        }

        public void Activate(bool active)
        {
            LastUpdate = DateTime.Now;
            Active = active;
        }
    }
}