// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class DateStamp
    {
        public int NumberOfUpdates { get; protected set; }
        public DateTime CreationDate { get; protected set; }
        public DateTime LastUpdate { get; set; }
    }
}