// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class AddressEntity : BaseEntity
    {
        public AddressEntity()
        {
            People = new HashSet<People>();
        }

        [Key]
        public Guid Id { get; private set; }
        [Required]
        [Column("Address")]
        [StringLength(255)]
        public string AddressValue { get; private set; }
        public int Number { get; private set; }
        [Required]
        [StringLength(255)]
        public string Neighborhood { get; private set; }
        [Required]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; private set; }

        [InverseProperty("Address")]
        public virtual ICollection<People> People { get; private set; }

        public AddressEntity(string addressValue, int number, string neighborhood, string cep)
        {
            Id = Guid.NewGuid();
            AddressValue = addressValue;
            Number = number;
            Neighborhood = neighborhood;
            Cep = cep;
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }

        public void UpdateAsync(Guid id, string addressValue, int number, string neighborhood, string cep)
        {
            AddressValue = addressValue;
            Number = number;
            Neighborhood = neighborhood;
            Cep = cep;
            LastUpdate = DateTime.Now;
        }
    }
}