// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    public partial class Address
    {
        public Address()
        {
            People = new HashSet<People>();
        }

        [Key]
        public Guid Id { get; set; }

        [Required]
        [Column("Address")]
        [StringLength(255)]
        public string Address1 { get; set; }

        public int Number { get; set; }

        [Required]
        [StringLength(255)]
        public string Neighborhood { get; set; }

        [Required]
        [StringLength(8)]
        [Unicode(false)]
        public string Cep { get; set; }

        [InverseProperty("Address")]
        public virtual ICollection<People> People { get; set; }
    }
}