// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    public partial class Assessment
    {
        public Assessment()
        {
            Grades = new HashSet<Grades>();
        }

        [Key]
        public Guid Id { get; private set; }
        public Guid? SubjectId { get; private set; }

        [ForeignKey("SubjectId")]
        [InverseProperty("Assessment")]
        public virtual Subject Subject { get; private set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<Grades> Grades { get; private set; }

        [Required]
        public DateTime LastUpdate { get; private set; }

        [Required]
        public DateTime RegistrationDate { get; private set; }


        public Assessment(Guid id, Guid? subjectId, Subject subject, ICollection<Grades> grades)
        {
            Id = id;
            SubjectId = subjectId;
            Subject = subject;
            Grades = grades;
            LastUpdate = DateTime.Now;
            RegistrationDate = DateTime.Now;
        }

        public void Update(Guid id, Guid? subjectId, Subject subject, ICollection<Grades> grades)
        {
            Id = id;
            SubjectId = subjectId;
            Subject = subject;
            Grades = grades;
            LastUpdate = DateTime.Now;
        }
    }
}