// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Assessment : BaseEntity
    {
        public Assessment()
        {
            Grades = new HashSet<Grades>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid? SubjectId { get; set; }

        [ForeignKey("SubjectId")]
        [InverseProperty("Assessment")]
        public virtual Subject Subject { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<Grades> Grades { get; set; }
    }
}