// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Class : BaseEntity
    {
        public Class()
        {
            Subject = new HashSet<Subject>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        public string FullName { get; set; }
        public int EnrolledStudents { get; set; }
        public int Shift { get; set; }
        [Required]
        [StringLength(255)]
        public string Room { get; set; }

        [InverseProperty("Class")]
        public virtual ICollection<Subject> Subject { get; set; }
    }
}