// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Grades
    {
        public Grades()
        {
            ReportCard = new HashSet<ReportCard>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid AssessmentId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Grade { get; set; }

        [ForeignKey("AssessmentId")]
        [InverseProperty("Grades")]
        public virtual Assessment Assessment { get; set; }
        [InverseProperty("Grades")]
        public virtual ICollection<ReportCard> ReportCard { get; set; }
    }
}