// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    public partial class Grades
    {
        public Grades()
        {
            ReportCard = new HashSet<ReportCard>();
        }

        [Key]
        public Guid Id { get; private set; }
        public Guid AssessmentId { get; private set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Grade { get; private set; }

        [ForeignKey("AssessmentId")]
        [InverseProperty("Grades")]
        public virtual Assessment Assessment { get; private set; }
        [InverseProperty("Grades")]
        public virtual ICollection<ReportCard> ReportCard { get; private set; }

        [Required]
        public DateTime LastUpdate { get; private set; }

        [Required]
        public DateTime RegistrationDate { get; private set; }

        public Grades(Guid id, Guid assessmentId, decimal? grade, Assessment assessment, ICollection<ReportCard> reportCard)
        {
            Id = id;
            AssessmentId = assessmentId;
            Grade = grade;
            Assessment = assessment;
            ReportCard = reportCard;
            LastUpdate = DateTime.Now;
            RegistrationDate = DateTime.Now;
        }

        public void Update(Guid id, Guid assessmentId, decimal? grade, Assessment assessment, ICollection<ReportCard> reportCard)
        {
            Id = id;
            AssessmentId = assessmentId;
            Grade = grade;
            Assessment = assessment;
            ReportCard = reportCard;
            LastUpdate = DateTime.Now;
        }
    }
}