// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace UniVerseAPI.Infra.Data.Context
{
    [Index("Cpf", Name = "UQ__People__C1FF9309991D9366", IsUnique = true)]
    public partial class People : BaseEntity
    {
        [Key]
        public Guid Id { get; set; }
        public Guid AddressId { get; set; }
        [Required]
        [StringLength(255)]
        public string FullName { get; set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Required]
        [StringLength(255)]
        public string Gender { get; set; }
        [Required]
        [StringLength(255)]
        public string Phone { get; set; }
        [Required]
        [StringLength(255)]
        public string Email { get; set; }
        [Required]
        [StringLength(500, MinimumLength = 8)]
        public string Password { get; set; }

        [ForeignKey("AddressId")]
        [InverseProperty("People")]
        public virtual AddressEntity AddressEntity { get; set; }
        [InverseProperty("People")]
        public virtual ICollection<Student> Student { get; set; }
        [InverseProperty("People")]
        public virtual ICollection<Teacher> Teacher { get; set; }

        public People()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }
    }


}