// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = System.ComponentModel.DataAnnotations.Schema.IndexAttribute;

namespace UniVerseAPI.Models
{
    public partial class People
    {
        public People()
        {
            Student = new HashSet<Student>();
            Teacher = new HashSet<Teacher>();
        }

        [Key]
        public Guid Id { get; private set; }
        public Guid AddressId { get; private set; }
        [Required]
        [StringLength(255)]
        public string FullName { get; private set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; private set; }
        public bool Active { get; private set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string Cpf { get; private set; }
        [Required]
        [StringLength(255)]
        public string Gender { get; private set; }
        [Required]
        [StringLength(255)]
        public string Phone { get; private set; }
        [Required]
        [StringLength(255)]
        public string Email { get; private set; }
        public bool Deleted { get; private set; }

        [ForeignKey("AddressId")]
        [InverseProperty("People")]
        public virtual Address Address { get; private set; }
        [InverseProperty("People")]
        public virtual ICollection<Student> Student { get; private set; }
        [InverseProperty("People")]
        public virtual ICollection<Teacher> Teacher { get; private set; }

        [Required]
        public DateTime LastUpdate { get; private set; }

        [Required]
        public DateTime RegistrationDate { get; private set; }

        public People(Guid id, Guid addressId, string fullName, DateTime birthDate, bool active, string cpf, string gender, string phone, string email, bool deleted, Address address, ICollection<Student> student, ICollection<Teacher> teacher)
        {
            Id = id;
            AddressId = addressId;
            FullName = fullName;
            BirthDate = birthDate;
            Active = active;
            Cpf = cpf;
            Gender = gender;
            Phone = phone;
            Email = email;
            Deleted = deleted;
            Address = address;
            Student = student;
            Teacher = teacher;
            LastUpdate = DateTime.Now;
            RegistrationDate = DateTime.Now;
        }

        public void Update(Guid id, Guid addressId, string fullName, DateTime birthDate, bool active, string cpf, string gender, string phone, string email, bool deleted, Address address, ICollection<Student> student, ICollection<Teacher> teacher)
        {
            Id = id;
            AddressId = addressId;
            FullName = fullName;
            BirthDate = birthDate;
            Active = active;
            Cpf = cpf;
            Gender = gender;
            Phone = phone;
            Email = email;
            Deleted = deleted;
            Address = address;
            Student = student;
            Teacher = teacher;
            LastUpdate = DateTime.Now;
        }
    }
}