// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    public partial class ReportCard
    {
        public ReportCard()
        {
            Student = new HashSet<Student>();
        }

        [Key]
        public Guid Id { get; private set; }
        public Guid GradesId { get; private set; }
        public Guid SubjectId { get; private set; }
        public Guid PeriodId { get; private set; }

        [ForeignKey("GradesId")]
        [InverseProperty("ReportCard")]
        public virtual Grades Grades { get; private set; }
        [ForeignKey("PeriodId")]
        [InverseProperty("ReportCard")]
        public virtual Period Period { get; private set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("ReportCard")]
        public virtual Subject Subject { get; private set; }
        [InverseProperty("ReportCard")]
        public virtual ICollection<Student> Student { get; private set; }

        [Required]
        public DateTime LastUpdate { get; private set; }

        [Required]
        public DateTime RegistrationDate { get; private set; }

        public ReportCard(Guid id, Guid gradesId, Guid subjectId, Guid periodId, Grades grades, Period period, Subject subject, ICollection<Student> student)
        {
            Id = id;
            GradesId = gradesId;
            SubjectId = subjectId;
            PeriodId = periodId;
            Grades = grades;
            Period = period;
            Subject = subject;
            Student = student;
            LastUpdate = DateTime.Now;
            RegistrationDate = DateTime.Now;
        }

        public void Update(Guid id, Guid gradesId, Guid subjectId, Guid periodId, Grades grades, Period period, Subject subject, ICollection<Student> student)
        {
            Id = id;
            GradesId = gradesId;
            SubjectId = subjectId;
            PeriodId = periodId;
            Grades = grades;
            Period = period;
            Subject = subject;
            Student = student;
            LastUpdate = DateTime.Now;
        }
    }
}