// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class ReportCard : BaseEntity
    {
        public ReportCard()
        {
            Student = new HashSet<Student>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid GradesId { get; set; }
        public Guid SubjectId { get; set; }
        public Guid PeriodId { get; set; }

        [ForeignKey("GradesId")]
        [InverseProperty("ReportCard")]
        public virtual Grades Grades { get; set; }
        [ForeignKey("PeriodId")]
        [InverseProperty("ReportCard")]
        public virtual Period Period { get; set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("ReportCard")]
        public virtual Subject Subject { get; set; }
        [InverseProperty("ReportCard")]
        public virtual ICollection<Student> Student { get; set; }
    }
}