// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UniVerseAPI.Models
{
    public partial class Student
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ReportCardId { get; set; }
        public Guid PeopleId { get; set; }
        public Guid CourseId { get; set; }
        public int Registration { get; set; }
        public bool? Deleted { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Student")]
        public virtual Course Course { get; set; }

        [ForeignKey("PeopleId")]
        [InverseProperty("Student")]
        public virtual People People { get; set; }

        [ForeignKey("ReportCardId")]
        [InverseProperty("Student")]
        public virtual ReportCard ReportCard { get; set; }

        public Student(Guid reportCardId, Guid peopleId, Guid courseId, int registration)
        {
            Id = Guid.NewGuid(); ;
            ReportCardId = reportCardId;
            PeopleId = peopleId;
            CourseId = courseId;
            Registration = registration;
        }

        public void Update(Guid reportCardId, Guid peopleId, Guid courseId, int registration, bool deleted)
        {
            Id = Guid.NewGuid(); ;
            ReportCardId = reportCardId;
            PeopleId = peopleId;
            CourseId = courseId;
            Registration = registration;
        }
    }
}