// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace UniVerseAPI.Models
{
    [Index("Code", Name = "UQ__Teacher__A25C5AA792072F3C", IsUnique = true)]
    public partial class Teacher
    {
        public Teacher()
        {
            Subject = new HashSet<Subject>();
        }

        [Key]
        public Guid Id { get; private set; }
        public Guid PeopleId { get; private set; }
        [Required]
        [StringLength(255)]
        public string Code { get; private set; }
        public bool Deleted { get; private set; }

        [ForeignKey("PeopleId")]
        [InverseProperty("Teacher")]
        public virtual People People { get; private set; }
        [InverseProperty("Teacher")]
        public virtual ICollection<Subject> Subject { get; private set; }

        [Required]
        public DateTime LastUpdate { get; private set; }

        [Required]
        public DateTime RegistrationDate { get; private set; }

        public Teacher(Guid id, Guid peopleId, string code, bool deleted, People people, ICollection<Subject> subject)
        {
            Id = id;
            PeopleId = peopleId;
            Code = code;
            Deleted = deleted;
            People = people;
            Subject = subject;
            LastUpdate = DateTime.Now;
            RegistrationDate = DateTime.Now;
        }

        public void Update(Guid id, Guid peopleId, string code, bool deleted, People people, ICollection<Subject> subject)
        {
            Id = id;
            PeopleId = peopleId;
            Code = code;
            Deleted = deleted;
            People = people;
            Subject = subject;
            LastUpdate = DateTime.Now;

        }
    }
}