// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class User : BaseEntity
    {
        public Guid Id { get; private set; }
        public Guid RoleId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RefreshToken { get; set; }
        public DateTime RefreshTokenValidity { get; set; }

        [InverseProperty("User")]
        public virtual People People { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("User")]
        public virtual Roles Roles { get; set; }

        public User()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }
    }
}