// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Class : DateStamp
    {
        public Class()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
            Students = new List<Student>();
        }

        public Guid Id { get; set; }
        public string FullName { get; set; }
        public int Code { get; set; }
        public string Shift { get; set; }
        public string Room { get; set; }

        [InverseProperty("Class")]
        public virtual ICollection<Subject> Subject { get; set; }

        [InverseProperty("Classes")]
        public virtual List<Student> Students { get; set; }

    }
}