// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Student : BaseEntity
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? ReportCardId { get; set; }
        public Guid PeopleId { get; set; }
        public Guid? CourseId { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 20)]
        [Unicode(true)]
        public string Registration { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Student")]
        public virtual Course Course { get; set; }
        [ForeignKey("PeopleId")]
        [InverseProperty("Student")]
        public virtual People People { get; set; }
        [ForeignKey("ReportCardId")]
        [InverseProperty("Student")]
        public virtual ReportCard ReportCard { get; set; }

        public Student()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }

        public Student(Guid peopleId, Guid courseId, string registration)
        {
            Id = Guid.NewGuid();
            PeopleId = peopleId;
            CourseId = courseId;
            Registration = registration;
            Active = true;
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }

        public void UpdateAsync(Guid? courseId, Guid? reportCardId)
        {
            ReportCardId = reportCardId;
            CourseId = courseId;
            LastUpdate = DateTime.Now;
        }

        public void CourseTransfer(Guid courseId)
        {
            CourseId = courseId;
            LastUpdate = DateTime.Now;
        }
    }
}


