// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Student : BaseEntity
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? ReportCardId { get; set; }
        public Guid PeopleId { get; set; }
        public Guid? CourseId { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 20)]
        [Unicode(true)]
        public string Registration { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Student")]
        public virtual Course Course { get; set; }
        [ForeignKey("PeopleId")]
        [InverseProperty("Student")]
        public virtual People People { get; set; }
        [ForeignKey("ReportCardId")]
        [InverseProperty("Student")]
        public virtual ReportCard ReportCard { get; set; }

        public Student()
        {
        }

        public Student(Guid peopleId, Guid courseId, string registration)
        {
            Id = Guid.NewGuid();
            PeopleId = peopleId;
            CourseId = courseId;
            Registration = registration;
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }

        public void UpdateAsync(Guid reportCardId, Guid peopleId, Guid courseId, string registration, bool deleted)
        {
            ReportCardId = reportCardId;
            PeopleId = peopleId;
            CourseId = courseId;
            Registration = registration;
            Deleted = deleted;
            LastUpdate = DateTime.Now;
        }
    }
}


//"CourseCode": [
//      "The CourseCode field is required."
//    ],
//    "People.Cpf": [
//      "The Cpf field is required."
//    ],
//    "People.Email": [
//      "The Email field is required."
//    ],
//    "People.Phone": [
//      "The Phone field is required."
//    ],
//    "People.Gender": [
//      "The Gender field is required."
//    ],
//    "People.FullName": [
//      "The FullName field is required."
//    ],
//    "Address.Cep": [
//      "The Cep field is required."
//    ],
//    "Address.AddressValue": [
//      "The AddressValue field is required."
//    ],
//    "Address.Neighborhood": [
//      "The Neighborhood field is required."
//    ]