// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Subject : DateStamp
    {
        [Key]
        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public Guid TeacherId { get; set; }
        public Guid ClassId { get; set; }
        public Guid? PeriodId { get; set; }

        public string FullName { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public DateTime Workload { get; set; }

        [ForeignKey("ClassId")]
        [InverseProperty("Subject")]
        public virtual Class Class { get; set; }
        [ForeignKey("CourseId")]
        [InverseProperty("Subject")]
        public virtual Course Course { get; set; }
        [ForeignKey("TeacherId")]
        [InverseProperty("Subject")]
        public virtual Teacher Teacher { get; set; }

        [InverseProperty("Subject")]
        public virtual ICollection<Grades> Grades { get; }

        public Subject()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }
    }
}