// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class Teacher : BaseEntity
    {
        public Guid Id { get; set; }
        public Guid PeopleId { get; set; }
        public string Code { get; set; }
        public bool? Deleted { get; set; }
        public bool? Active { get; set; }

        [ForeignKey("PeopleId")]
        [InverseProperty("Teacher")]
        public virtual People People { get; set; }

        [InverseProperty("Teacher")]
        public virtual ICollection<Subject> Subject { get; set; }

        public Teacher()
        {
            Id = Guid.NewGuid();
            CreationDate = DateTime.Now;
            LastUpdate = DateTime.Now;
        }
    }
}