// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    public partial class Course
    {
        public Course()
        {
            Student = new HashSet<Student>();
            Subject = new HashSet<Subject>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        public string FullName { get; set; }
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime EndDate { get; set; }
        [Required]
        [StringLength(255)]
        public string Instructor { get; set; }
        public int Seats { get; set; }
        public int SpotsAvailable { get; set; }
        public int Price { get; set; }
        [Required]
        [StringLength(255)]
        public string Category { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty("Course")]
        public virtual ICollection<Student> Student { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Subject> Subject { get; set; }
    }
}