// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Models
{
    [Index("Code", Name = "UQ__Teacher__A25C5AA792072F3C", IsUnique = true)]
    public partial class Teacher
    {
        public Teacher()
        {
            Subject = new HashSet<Subject>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid PeopleId { get; set; }
        [Required]
        [StringLength(255)]
        public string Code { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("PeopleId")]
        [InverseProperty("Teacher")]
        public virtual People People { get; set; }
        [InverseProperty("Teacher")]
        public virtual ICollection<Subject> Subject { get; set; }
    }
}