// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class StudentInputDTO
    {
        [Required]
        [StringLength(20, MinimumLength = 20)]
        [Unicode(true)]
        public string Registration { get; set; }
        [Required]
        public AddressEntity Address { get; set; }
        [Required]
        public People People { get; set; }
        [Required]
        [StringLength(10, MinimumLength = 10)]
        [Unicode(true)]
        public string CourseCode { get; private set; }
    }
}