// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class TeacherInputDTO
    {
        [Required]
        [StringLength(255)]
        public string Code { get; set; }

        [Required]
        public AddressInputDTO Address { get; set; }

        [Required]
        public PeopleInputDTO People { get; set; }

    }
}