// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using UniVerseAPI.Application.DTOs.Request.Common;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class TeacherInputDTO
    {
        [Required]
        public PeopleInputDTO People { get; set; }
        [Required]
        public AddressInputDTO AddressEntity { get; set; }
        [Required]
        public LoginOrUserInputDTO User { get; set; }

    }
}