// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class AddressInputDTO : BaseEntity
    {
        [Required]
        [Column("Address")]
        [StringLength(255)]
        public string AddressValue { get; set; }
        public int Number { get; set; }
        [Required]
        [StringLength(255)]
        public string Neighborhood { get; set; }
        [Required]
        [StringLength(8)]
        [Unicode(true)]
        public string Cep { get; set; }
    }
}