// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class AddressInputDTO
    {
        [Required]
        [Column("Address")]
        [StringLength(255)]
        [Display(Name = "Address", Description = "Complete address")]
        public string AddressValue { get; set; }

        [Required]
        [Display(Name = "Number", Description = "House number")]
        public int Number { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Neighborhood")]
        public string Neighborhood { get; set; }

        [Required]
        [StringLength(8, MinimumLength = 8)]
        [Unicode(true)]
        [Display(Name = "Cep", Description = "Enter the zip code for your region")]
        public string Cep { get; set; }
    }
}