// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class GradeInputDTO
    {
        [Required]
        public string StudentRegistration { get; set; }

        [Required]
        public string SubjectCode { get; set; }

        [Required]
        [Range(0, 10)]
        [Display(Name = "First Note", Description = "Enter the first note")]
        public decimal? FirstNote { get; set; }

        [Range(0, 10)]
        [Display(Name = "Second Note", Description = "Enter the seconta note")]
        public decimal? SecondNote { get; set; }

        public bool? TookFinalExame { get; set; }

        [Range(0, 10)]
        public decimal? FinalExameGrade { get; set; }

        [Display(Name = "Situation", Description = "Inform the student's situation")]
        public bool Approved { get; set; }
    }
}