// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class GroupStudentClassInputDTO
    {
        [Required]
        [Display(Name = "Registration", Description = "Inform the student's registration")]
        public string StudentRegistration { get; set; }

        [Required]
        [Display(Name = "Class code", Description = "Enter the class code")]
        public int ClassCode { get; set; }
    }
}