// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class PeopleInputDTO : BaseEntity
    {
        [Required]
        [StringLength(255)]
        public string FullName { get; private set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; private set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string Cpf { get; private set; }
        [Required]
        [StringLength(255)]
        public string Gender { get; private set; }
        [Required]
        [StringLength(255)]
        public string Phone { get; private set; }
        [Required]
        [StringLength(255)]
        public string Email { get; private set; }
        [Required]
        [StringLength (500, MinimumLength = 8)]
        public string Password { get; set; }
    }


}