// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class UserInputDTO
    {
        [Required]
        [EmailAddress]
        [StringLength(255)]
        [Display(Name = "Address", Description = "Complete address")]
        public string Email { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 8)]
        [Display(Name = "Number", Description = "House number")]
        public string Password { get; set; }
    }
}