// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniVerseAPI.Infra.Data.Context
{
    public partial class StudentListResponseDTO
    {
        [Required]
        public Student Student { get; set; }

        [Required]
        public AddressEntity Address { get; set; }

        [Required]
        public People People { get; set; }

        public StudentListResponseDTO(Student student, AddressEntity address, People people)
        {
            Student = student;
            Address = address;
            People = people;
        }
    }
}