CREATE TABLE [Address] (
	Id UNIQUEIDENTIFIER NOT NULL,
	[Address] NVARCHAR(255) NOT NULL,
	Number INT NOT NULL,
	Neighborhood NVARCHAR(255) NOT NULL,
	Cep CHAR(8) NOT NULL,
  CONSTRAINT [PK_ADDRESS] PRIMARY KEY ([Id])

)
GO

CREATE TABLE [People] (
	Id UNIQUEIDENTIFIER NOT NULL,
	AddressId UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	BirthDate DATE NOT NULL,
	Active BIT NOT NULL DEFAULT(0),
	Cpf CHAR(11) NOT NULL UNIQUE,
	Gender NVARCHAR(255) NOT NULL,
	Phone NVARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	Deleted BIT NOT NULL DEFAULT(0),
  CONSTRAINT [PK_PEOPLE] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Student] (
	Id UNIQUEIDENTIFIER NOT NULL,
	ReportCardId UNIQUEIDENTIFIER NOT NULL,
	PeopleId UNIQUEIDENTIFIER NOT NULL,
	CourseId UNIQUEIDENTIFIER NOT NULL,
	Registration INT NOT NULL,
	Deleted BIT NOT NULL DEFAULT(0),
  CONSTRAINT [PK_STUDENT] PRIMARY KEY ([Id])
)
GO
CREATE TABLE [Teacher] (
	Id UNIQUEIDENTIFIER NOT NULL,
	PeopleId UNIQUEIDENTIFIER NOT NULL,
	Code NVARCHAR(255) NOT NULL UNIQUE,
	Deleted BIT NOT NULL DEFAULT(0),
  CONSTRAINT [PK_TEACHER] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Course] (
	Id UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	Instructor NVARCHAR(255) NOT NULL,
	Seats INT NOT NULL,
	SpotsAvailable INT NOT NULL,
	Price INT NOT NULL,
	Category NVARCHAR(255) NOT NULL,
	Active BIT NOT NULL DEFAULT(0),
	Deleted BIT NOT NULL DEFAULT(0),
  CONSTRAINT [PK_COURSE] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Subject] (
	Id UNIQUEIDENTIFIER NOT NULL,
	CourseId UNIQUEIDENTIFIER NOT NULL,
	TeacherId UNIQUEIDENTIFIER NOT NULL,
	ClassId UNIQUEIDENTIFIER,
	PeriodId UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	Code CHAR(10) NOT NULL,
	[Workload] DATE NOT NULL,
	Instructor NVARCHAR(255) NOT NULL,
  CONSTRAINT [PK_SUBJECT] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Assessment] (
	Id UNIQUEIDENTIFIER NOT NULL,
	SubjectId UNIQUEIDENTIFIER,
  CONSTRAINT [PK_ASSESSMENT] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Grades] (
	Id UNIQUEIDENTIFIER NOT NULL,
	AssessmentId UNIQUEIDENTIFIER NOT NULL,
	Grade DECIMAL DEFAULT(0),
  CONSTRAINT [PK_GRADES] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Class] (
	Id UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	EnrolledStudents INT NOT NULL,
	Shift INT NOT NULL,
	Room NVARCHAR(255) NOT NULL,
  CONSTRAINT [PK_CLASS] PRIMARY KEY ([Id])

)
GO
CREATE TABLE [Period] (
	Id UNIQUEIDENTIFIER NOT NULL,
	[FullName] NVARCHAR(255) NOT NULL,
	EnrolledStudents INT NOT NULL,
	Room NVARCHAR(255) NOT NULL,
  CONSTRAINT [PK_PERIOD] PRIMARY KEY ([Id])

)
GO

CREATE TABLE [ReportCard] (
	Id UNIQUEIDENTIFIER NOT NULL,
	GradesId UNIQUEIDENTIFIER NOT NULL,
	SubjectId UNIQUEIDENTIFIER NOT NULL,
	PeriodId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT [PK_REPORTCARD] PRIMARY KEY ([Id])

)
GO
ALTER TABLE [Student] WITH CHECK ADD CONSTRAINT [Student_fk0] FOREIGN KEY ([ReportCardId]) REFERENCES [ReportCard]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Student] CHECK CONSTRAINT [Student_fk0]
GO
ALTER TABLE [Student] WITH CHECK ADD CONSTRAINT [Student_fk1] FOREIGN KEY ([PeopleId]) REFERENCES [People]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Student] CHECK CONSTRAINT [Student_fk1]
GO
ALTER TABLE [Student] WITH CHECK ADD CONSTRAINT [Student_fk2] FOREIGN KEY ([CourseId]) REFERENCES [Course]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Student] CHECK CONSTRAINT [Student_fk2]
GO


ALTER TABLE [Subject] WITH CHECK ADD CONSTRAINT [Subject_fk0] FOREIGN KEY ([CourseId]) REFERENCES [Course]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Subject] CHECK CONSTRAINT [Subject_fk0]
GO
ALTER TABLE [Subject] WITH CHECK ADD CONSTRAINT [Subject_fk1] FOREIGN KEY ([TeacherId]) REFERENCES [Teacher]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Subject] CHECK CONSTRAINT [Subject_fk1]
GO
ALTER TABLE [Subject] WITH CHECK ADD CONSTRAINT [Subject_fk2] FOREIGN KEY ([ClassId]) REFERENCES [Class]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Subject] CHECK CONSTRAINT [Subject_fk2]
GO
ALTER TABLE [Subject] WITH CHECK ADD CONSTRAINT [Subject_fk3] FOREIGN KEY ([PeriodId]) REFERENCES [Period]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Subject] CHECK CONSTRAINT [Subject_fk3]
GO


ALTER TABLE [Grades] WITH CHECK ADD CONSTRAINT [Grades_fk0] FOREIGN KEY ([AssessmentId]) REFERENCES [Assessment]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Grades] CHECK CONSTRAINT [Grades_fk0]
GO

ALTER TABLE [Teacher] WITH CHECK ADD CONSTRAINT [Teacher_fk0] FOREIGN KEY ([PeopleId]) REFERENCES [People]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Teacher] CHECK CONSTRAINT [Teacher_fk0]
GO
ALTER TABLE [People] WITH CHECK ADD CONSTRAINT [People_fk0] FOREIGN KEY ([AddressId]) REFERENCES [Address]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [People] CHECK CONSTRAINT [People_fk0]
GO
ALTER TABLE [Assessment] WITH CHECK ADD CONSTRAINT [Assessment_fk0] FOREIGN KEY ([SubjectId]) REFERENCES [Subject]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Assessment] CHECK CONSTRAINT [Assessment_fk0]
GO

ALTER TABLE [ReportCard] ADD CONSTRAINT FK_GRADES
FOREIGN KEY (GradesId) REFERENCES Grades (Id);
GO

ALTER TABLE [ReportCard] ADD CONSTRAINT FK_SUBJECT
FOREIGN KEY (SubjectId) REFERENCES [Subject] (Id);
GO

ALTER TABLE [ReportCard] ADD CONSTRAINT FK_PERIOD
FOREIGN KEY (PeriodId) REFERENCES [Period] (Id);
GO
